Export without argument
t-h2o/42-minishell pull request #31
Opened 2022-06-18 15:48 UTC by t-h2o

2022-06-18 16:03 UTC, lgyger reviewed
You should check if the environment is empty then, simply return so that there is no uneccessary malloc. Otherwise well done for creating such a clear, efficient and well structured code

2022-06-19 08:27 UTC, lgyger requested changes
checked the environment and added an inline

2022-06-19 08:27 UTC, lgyger commented on srcs/export_no_arg.c
> +	n = count(envp);
```suggestion
	int		n;
        if (!envp || !envp[0])
            return ;
	n = count(envp);
```

2022-06-19 08:27 UTC, lgyger commented on srcs/export_no_arg.c
> +static void	swap(char **a, char **b)
```suggestion
static inline void	swap(char **a, char **b)
```

2022-06-19 11:16 UTC, t-h2o reviewed
Redo the same review

2022-06-19 11:16 UTC, t-h2o commented on srcs/export_no_arg.c
> +	n = count(envp);
```suggestion
    if (!envp || !envp[0])
            return ;
	n = count(envp);
```

2022-06-19 11:16 UTC, t-h2o commented on srcs/export_no_arg.c
> +static void	swap(char **a, char **b)
```suggestion
static inline void	swap(char **a, char **b)
```

2022-06-19 11:21 UTC, merged